// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Xqxlv6b8K1DwmDdhRtOmXHkJD_A-9s8',
    appId: '1:540512471949:web:0f63363a1c57a5c88ccbc4',
    messagingSenderId: '540512471949',
    projectId: 'spendsense-2ca09',
    authDomain: 'spendsense-2ca09.firebaseapp.com',
    storageBucket: 'spendsense-2ca09.firebasestorage.app',
    measurementId: 'G-HTB4ENVKQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbwCVVihlV9U0q1WfEdhVu6GttcY2IL2c',
    appId: '1:540512471949:android:a3188d77df1f79eb8ccbc4',
    messagingSenderId: '540512471949',
    projectId: 'spendsense-2ca09',
    storageBucket: 'spendsense-2ca09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWLauFXVb-YQpRXG5Rza8P4ZAKTJapQ_Q',
    appId: '1:540512471949:ios:90e6921078bf31e78ccbc4',
    messagingSenderId: '540512471949',
    projectId: 'spendsense-2ca09',
    storageBucket: 'spendsense-2ca09.firebasestorage.app',
    iosBundleId: 'com.example.spendsense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWLauFXVb-YQpRXG5Rza8P4ZAKTJapQ_Q',
    appId: '1:540512471949:ios:90e6921078bf31e78ccbc4',
    messagingSenderId: '540512471949',
    projectId: 'spendsense-2ca09',
    storageBucket: 'spendsense-2ca09.firebasestorage.app',
    iosBundleId: 'com.example.spendsense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3Xqxlv6b8K1DwmDdhRtOmXHkJD_A-9s8',
    appId: '1:540512471949:web:095cf28e4a4cc7ca8ccbc4',
    messagingSenderId: '540512471949',
    projectId: 'spendsense-2ca09',
    authDomain: 'spendsense-2ca09.firebaseapp.com',
    storageBucket: 'spendsense-2ca09.firebasestorage.app',
    measurementId: 'G-7ZXFJZ55DN',
  );
}
